spring:
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB

zuul:
  max:
    host:
      connections: 1000000
      host:
        maxTotalConnections: 6000000
        maxPerRouteConnections: 600000
  routes:
    uac-route:
      path: /uac/**
      sensitiveHeaders:
#      strip-prefix: false
      service-id: uac
      
    admin-route:
      path: /admin/**
      sensitiveHeaders:
      service-id: admin
      
    order-route:
      path: /order/**
      sensitiveHeaders:
      service-id: order
    doc-route:
      path: /doc/**
      sensitiveHeaders:
      service-id: doc
      
  add-proxy-headers: true
  add-host-header: true

ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  
hystrix:
  command:
    c4i-store:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 6000000
            ribbon:
              ReadTimeout: 600000
              ConnectTimeout: 600000 
security:
  oauth2:
    client:
      clientId: gateway
      clientSecret: sccloud
      access-token-uri: http://localhost:7979/uac/oauth/token
      user-authorization-uri: http://localhost:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://localhost:7979/uac/user
      prefer-token-info: false
      jwt:
        key-uri: http://localhost:8000/oauth/token_key
    

proxy:
  auth:
    routes:
      uac-route: oauth2
      admin-route: oauth2
      order-route: oauth2